# Generated by Django 4.2.11 on 2025-12-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('country_code', models.CharField(choices=[('+966', 'Saudi Arabia (+966)'), ('+971', 'UAE (+971)'), ('+965', 'Kuwait (+965)'), ('+973', 'Bahrain (+973)'), ('+974', 'Qatar (+974)'), ('+968', 'Oman (+968)'), ('+20', 'Egypt (+20)'), ('+962', 'Jordan (+962)'), ('+961', 'Lebanon (+961)'), ('+963', 'Syria (+963)'), ('+964', 'Iraq (+964)'), ('+967', 'Yemen (+967)'), ('+218', 'Libya (+218)'), ('+212', 'Morocco (+212)'), ('+213', 'Algeria (+213)'), ('+216', 'Tunisia (+216)'), ('+249', 'Sudan (+249)'), ('+1', 'USA/Canada (+1)'), ('+44', 'UK (+44)')], default='+966', max_length=5)),
                ('phone', models.CharField(help_text='WhatsApp number without country code', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Imam',
                'verbose_name_plural': 'Imams',
            },
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Mosque',
                'verbose_name_plural': 'Mosques',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(5, 'Saturday'), (6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], verbose_name='Weekday')),
                ('prayer_time', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], default='dhuhr', max_length=10, verbose_name='Prayer Time')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.imam', verbose_name='Imam')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mosque', verbose_name='Mosque')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'unique_together': {('mosque', 'weekday', 'prayer_time')},
            },
        ),
    ]
