# Generated by Django 4.2.11 on 2026-01-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_imam_options_alter_schedule_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='country_code',
            field=models.CharField(blank=True, choices=[('+966', 'Saudi Arabia (+966)'), ('+971', 'UAE (+971)'), ('+965', 'Kuwait (+965)'), ('+973', 'Bahrain (+973)'), ('+974', 'Qatar (+974)'), ('+968', 'Oman (+968)'), ('+20', 'Egypt (+20)'), ('+962', 'Jordan (+962)'), ('+961', 'Lebanon (+961)'), ('+963', 'Syria (+963)'), ('+964', 'Iraq (+964)'), ('+967', 'Yemen (+967)'), ('+218', 'Libya (+218)'), ('+212', 'Morocco (+212)'), ('+213', 'Algeria (+213)'), ('+216', 'Tunisia (+216)'), ('+249', 'Sudan (+249)'), ('+1', 'USA/Canada (+1)'), ('+44', 'UK (+44)')], default='+966', max_length=5),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number without country code', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='prayer_time',
            field=models.CharField(choices=[('fajr', 'الفجر'), ('dhuhr', 'الظهر'), ('asr', 'العصر'), ('maghrib', 'المغرب'), ('isha', 'العشاء')], default='dhuhr', max_length=10, verbose_name='Prayer Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'السبت'), (1, 'الأحد'), (2, 'الإثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس'), (6, 'الجمعة')], verbose_name='Weekday'),
        ),
    ]
